language: php
php: ["5.6"]
sudo: false
dist: trusty

before_script:
 - echo | pecl install channel://pecl.php.net/yaml-2.0.2
 - echo | pecl install channel://pecl.php.net/pthreads-3.1.6
 - mkdir "$TRAVIS_BUILD_DIR"/../PocketMine && cd "$TRAVIS_BUILD_DIR"/../PocketMine
 - wget -O PocketMine-MP.phar "${1:-"https://github.com/pmmp/PocketMine-MP/releases/download/1.6.1dev-87/PocketMine-MP_1.6.1dev-87_e51a2725_API-2.1.0.phar"}"
 - mkdir plugins && wget -O plugins/PluginChecker.phar https://github.com/jasonwynn10/MyPlot/releases/download/1.1.9/PluginChecker.phar
 - mkdir unstaged
 - wget -O - https://poggit.pmmp.io/res/travisPluginTest.php | php -- unstaged

script:
- "if [ -f ${TRAVIS_BUILD_DIR}/../PocketMine/unstaged/MyPlot.phar ] ; then wget -O - https://poggit.pmmp.io/res/travisScript.sh | bash -s - MyPlot MyPlot ; else true ; fi"
- cd "$TRAVIS_BUILD_DIR"/../PocketMine/
- sed -i 's/world/Plots/' server.properties
- "if [ -f ${TRAVIS_BUILD_DIR}/../PocketMine/unstaged/MyPlot.phar ] ; then wget -O - https://poggit.pmmp.io/res/travisScript.sh | bash -s - MyPlot MyPlot ; else true ; fi"